### ISSUE TITLE
Create a new resource and data-source for "contract_to_l3out_epg"

### ISSUE THREAD

**Issue by diyvol777** [CiscoDevNet/terraform-provider-aci#1032] opened 2023-04-04 06:04 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello, we have some fabrics which are using l3out epg in common tennat for shared access. To get access from another tenant I need to add contract to context in tenant1(consumer) and l3epg (provider) in common tenant. I do it by hand.

### New or Affected Resource(s) + ACI Class(es):

* aci_XXXXX + fv:XXXX

### APIC version and APIC Platform

APIC version is 5.2(4d)

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by lhercot** [comment] 2023-04-05 22:40
Hi @diyvol777 , you can use aci_epg_to_contract resource to link to the external epg. Just pass the .id value of the external EPG to the application_epg_dn attribute.

aci_epg_to_contract documenation: https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/resources/epg_to_contract

**Comment by lhercot** [comment] 2023-04-05 22:41
Closing as this is a duplicate of #1023

**Closed by lhercot** 2023-04-05 22:41 UTC
Labels: enhancement
