### ISSUE TITLE
Missing resources to "apply" service graph template e.g. `vnsLDevVip`

### ISSUE THREAD

**Issue by jamesbtate** [CiscoDevNet/terraform-provider-aci#626] opened 2021-09-27 20:59 UTC
I'm trying to do a complete build-out of a L4-L7 service-graph template in L3/GoTo mode using an unmanaged device. It seems some required resources are not present in the provider.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.0.7
on linux_amd64
+ provider registry.terraform.io/ciscodevnet/aci v0.7.1
```

### APIC version and APIC Platform

* V 5.2.2f and on-prem.

### Affected Resource(s)

APIC classes:
* vnsLDevVip
* vnsLIf
* vnsCDev
* vnsCIf

### Expected Behavior

Expecting a resource called `aci_logical_device` or `aci_l4_l7_device` or similar. Similarly expecting a resource for the other classes mentioned above.

### Actual Behavior

These resources are not present.

### References

* [Cisco APIC Layer 4 to Layer 7 Services Deployment Guide](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/sw/1-x/L4-L7_Services_Deployment/guide/b_L4L7_Deploy/b_L4L7_Deploy_chapter_01100.html)

**Comment by lhercot** [comment] 2021-09-27 21:09
Duplicate #588

**Comment by lhercot** [comment] 2021-09-27 21:12
Closing as this is a duplicate of #588

Always feel free to open new issues but please check if another issue is not yet open for the same issue. You can use the search bar on the top with the "In this repository" filter to see if there is any other issues referencing the same class.

**Closed by lhercot** 2021-09-27 21:12 UTC
