### ISSUE TITLE
Create new resource and data source for route profile redistribution in L3Out

### ISSUE THREAD

**Issue by shrsr** [CiscoDevNet/terraform-provider-aci#983] opened 2022-12-20 19:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### APIC version and APIC Platform

all

### Affected Resource(s)

New resource and data source
Example DN: uni/tn-module_l3out_tf_tenant/out-module_l3out/rsredistributePol-[route_profile2]-direct
Class: l3extRsRedistributePol

### Terraform Configuration Files
Equivalent rest managed resource-

```hcl
resource "aci_rest_managed" "l3out_route_profiles_for_redistribution" {
  for_each   = { for redistribution in var.route_profiles_for_redistribution : redistribution.source => redistribution }
  
  dn         = "${aci_l3_outside.l3out.id}/rsredistributePol-[${split("prof-", each.value.route_map_dn)[1]}]-${each.value.source}"
  class_name = "l3extRsRedistributePol"
  content = {
    src = each.value.source
    tnRtctrlProfileName = split("prof-", each.value.route_map_dn)[1]
  }
}
```

**Comment by lhercot** [comment] 2023-12-21 17:38
Duplicate of #932

**Closed** 2023-12-21 17:38 UTC
Labels: new-data-source, new-resource
