### ISSUE TITLE
“aci_access_generic” resource issue

### ISSUE THREAD

**Issue by kozhabergenova** [CiscoDevNet/terraform-provider-aci#1136] opened 2023-12-04 09:27 UTC
### Terraform Version

terraform -v
Terraform v1.3.6
on linux_amd64

+ provider[registry.terraform.io/ciscodevnet/aci]** 2.11.1

### APIC Version

Application Policy Infrastructure Controller
Version: 5.2(7g)

### Affected Resource(s)

resource “aci_access_generic”
resource “aci_epgs_using_function”

### Issue Description

Initially, I created 'aci_access_generic' and 'aci_epgs_using_function' resources inside the module for network creation within the code block.

I noticed that when attempting to change the AEP, rename, or remove the network, all the EPGs assigned to that specific AEP are also deleted. Considering that AEP is a Fabric Access Policy object responsible for Layer 2 connectivity in the fabric, the deletion of other EPGs is a critical concern. 

### Terraform Configuration Files

```hcl
locals {

  l3out_path = [for l in var.l3out : "${l.tenant}/out-${l.name}"]

  subnet       = cidrsubnet(var.gateway_address, 0, 0)
  gateway_only = cidrhost(local.subnet, 1)

}

data "aci_tenant" "common" {
  name = "common"
}

data "aci_vrf" "common" {
  tenant_dn = data.aci_tenant.common.id
  name      = "common_vrf"
}

resource "aci_application_profile" "app_profile" {
  tenant_dn   = var.tenant_os
  name        = "${var.name}_ap"
  description = "${var.name} ap"
}

data "aci_physical_domain" "physdom_dev" {
  name = "physdom_dev"
}

resource "aci_bridge_domain" "bridge_domain" {
  tenant_dn                   = var.tenant_os
  description                 = "Bridge Domain for ${var.name}"
  name                        = "vlan_${var.vlan_id}_bd"
  relation_fv_rs_ctx          = var.vrf_os
  optimize_wan_bandwidth      = "no"
  annotation                  = "tag_bd"
  arp_flood                   = "yes"
  ep_clear                    = "no"
  host_based_routing          = "no"
  intersite_bum_traffic_allow = "yes"
  intersite_l2_stretch        = "yes"
  ip_learning                 = "yes"
  limit_ip_learn_to_subnets   = "yes"
  mcast_allow                 = "no"
  multi_dst_pkt_act           = "bd-flood"
  bridge_domain_type          = "regular"
  unk_mac_ucast_act           = "proxy"
  unk_mcast_act               = "flood"
  vmac                        = "not-applicable"
  relation_fv_rs_bd_to_out    = local.l3out_path
}

resource "aci_application_epg" "application_epg" {
  application_profile_dn = aci_application_profile.app_profile.id
  relation_fv_rs_bd      = aci_bridge_domain.bridge_domain.id
  name                   = "${var.name}_epg"
  description            = "EPG for ${var.name}"
  annotation             = "tag_epg"
  exception_tag          = "0"
  flood_on_encap         = "disabled"
  has_mcast_source       = "no"
  is_attr_based_epg      = "no"
  match_t                = "AtleastOne"
  pc_enf_pref            = "unenforced"
  pref_gr_memb           = "exclude"
  prio                   = "unspecified"
  shutdown               = "no"
}

# From the provider documentation: name - (Required) The name of the user defined function object. Name must be "default".

resource "aci_access_generic" "epg_to_aep" {
  for_each                            = toset(var.aep)
  attachable_access_entity_profile_dn = var.aep_common[each.key]
  name                                = "default"
}

resource "aci_epgs_using_function" "epg_to_aep_assign" {
  for_each          = toset(var.aep)
  access_generic_dn = aci_access_generic.epg_to_aep[each.key].id
  tdn   = aci_application_epg.application_epg.id
  encap = "vlan-${var.vlan_id}"
  mode  = var.mode
}

resource "aci_epg_to_domain" "net_2_domain" {
  application_epg_dn = aci_application_epg.application_epg.id
  tdn                = data.aci_physical_domain.physdom_dev.id
}

resource "aci_subnet" "subnet" {
  parent_dn   = aci_application_epg.application_epg.id
  ip          =  var.gateway_address
  preferred   = "no"
  scope       = var.route_scope
  description = "This subnet is created by terraform"
}
```
Input variables:
```
variable "name" {
  type = string
}

variable "vlan_id" {
  type = number
}

variable "gateway_address" {
  type = string
}

variable "route_scope" {
  type = list(string)
  default = ["public", "shared"]
}

variable "tenant_os" {
  type = string
}

variable "vrf_os" {
  type = string
}

variable "aep_common" {
  type = map(string)
}

variable "aep" {
  type = list(string)
}

variable "l3out" {
  type = list(object({
    name    = string
    tenant  = string
  }))
  default = []
  description = "If tenant doesn't have L3Out, it's not necessary to define it in BD"
}
```
Network module instance:
```
module "test_3" {
  source          = "./modules/networks"
  tenant_os       = module.common.tenant_common
  vrf_os          = module.common.vrf_common
  aep_common      = module.common.aaep
  aep             = ["compute", "provider"]
  name            = "test_3"
  vlan_id         = 102
  gateway_address = "10.10.12.1/24"
  l3out           = []
}
```

### Debug Output

I turn on the TF log and found this https://gist.github.com/kozhabergenova/0411ea49c454be4747200de9341745d9 

### Expected Behavior

The issue I observed is that when attempting to delete a specific EPG from the AEP, the deletion process impacts the entire path rather than just the targeted EPG. For example, instead of deleting the specific EPG from the AEP as expected:

uni/infra/attentp-aaep_compute/gen-default/rsfuncToEpg-[uni/tn-common/ap-test_3_ap/epg-test_3_epg]

### Actual Behavior

It unexpectedly destroys the entire path:

uni/infra/attentp-aaep_compute/gen-default

### Sum up

My question is, is this behavior expected? What is the role of the 'aci_access_generic' resource in this context, and why must its name be set to 'default'?

P.S. To address this issue, I implemented a workaround by defining the 'aci_access_generic' resource in a separate module. This allows me to create them only once for each AEP rather than creating them for each project network. I then export all 'aci_access_generic' resources outputs to the network module and selectively choose the specific ones in each instance of the module. This approach enables the deletion of 'aci_access_generic' resources without affecting other EPGs. However, questions above are still relevant.

**Comment by akinross** [comment] 2023-12-04 14:40
Hi @kozhabergenova,

I had a quick look at your issue but do not fully understand your issue here. I am able to manipulate individual resource defined with aci_epgs_using_function. I did a quick test without any looping constructs, but these should not make a difference in the behaviour. 

```
resource "aci_tenant" "abr_test_aep" {
  name = "abr_test_aep"
}

resource "aci_vrf" "abr_test_aep" {
  name      = "abr_test_aep_vrf"
  tenant_dn = aci_tenant.abr_test_aep.id
}

resource "aci_bridge_domain" "abr_test_aep" {
  name      = "abr_test_aep_bd"
  tenant_dn = aci_tenant.abr_test_aep.id
}

resource "aci_application_profile" "abr_test_aep" {
  name      = "abr_test_aep_ap"
  tenant_dn = aci_tenant.abr_test_aep.id
}

resource "aci_application_epg" "application_epg_1" {
  application_profile_dn = aci_application_profile.abr_test_aep.id
  relation_fv_rs_bd      = aci_bridge_domain.abr_test_aep.id
  name                   = "abr_test_aep_epg_1"
}

resource "aci_application_epg" "application_epg_2" {
  application_profile_dn = aci_application_profile.abr_test_aep.id
  relation_fv_rs_bd      = aci_bridge_domain.abr_test_aep.id
  name                   = "abr_test_aep_epg_2"
}

resource "aci_access_generic" "example" {
  attachable_access_entity_profile_dn = "uni/infra/attentp-abr_test_2"
  name                                = "default"
}

resource "aci_epgs_using_function" "epg_to_aep_assign_1" {
  access_generic_dn = aci_access_generic.example.id
  tdn               = aci_application_epg.application_epg_1.id
  encap             = "vlan-100"
  mode              = "regular"
}

resource "aci_epgs_using_function" "epg_to_aep_assign_2" {
  access_generic_dn = aci_access_generic.example.id
  tdn               = aci_application_epg.application_epg_2.id
  encap             = "vlan-200"
  mode              = "regular"
}
```

The aci_access_generic point to the infraGeneric class which is created as a container like holder for infraRsFuncToEpg class. So it is needed in order to bind the epg rs objects under the AEP. These modules both do not touch any epg object, the aci_access_generic should only create a relation to the epg. Are you sure your EPGs are being deleted?

When changing the AEP, renaming identifier properties like "tdn", "access_generic_dn" or "attachable_access_entity_profile_dn, you will trigger a ForceNew operation. This means the current object will be removed ( this behaviour is defined in aci would also impact it's children ) and then recreate it with the new object. When you would like to have the child configuration (infraRsFuncToEpg in your scenario) present then this should also be defined in terraform.

Thus also the remove of the aci_access_generic ( infraGeneric ) config that would mean all the infraRsFuncToEpg children attached to it. Similar behaviour is expected for any resource.

**Comment by kozhabergenova** [comment] 2024-01-03 11:49
Hi, I apologize for the delayed response.

> These modules both do not touch any epg object, the aci_access_generic should only create a relation to the epg. Are you sure your EPGs are being deleted? 

Affirmative, I'm certain about the issue because it resulted in a temporary outage in my production environment. My GitLab runner lost Layer 2 connectivity, and it took me some time to identify the problem and manually add the EPG to the specific AEP.

However, the root cause is not immediately apparent, mainly due to the inability to change the name of the resource. 

> When changing the AEP, renaming identifier properties like "tdn", "access_generic_dn" or "attachable_access_entity_profile_dn, you will trigger a ForceNew operation. This means the current object will be removed ( this behaviour is defined in aci would also impact it's children ) and then recreate it with the new object. When you would like to have the child configuration (infraRsFuncToEpg in your scenario) present then these should also be defined in terraform.

Yep, as i mentioned previously it just destroys the whole path:
uni/infra/attentp-aaep_compute/gen-default

I addressed this by specifying the access_generic_dn argument in aci_epgs_using_function like this: 
access_generic_dn = "${var.aep_access[each.key]}".

I just wanted to bring to your attention that this behavior was highly unexpected and has caused significant disruptions for me =)) Therefore, I suggest considering a modification in the future. For instance, each aci_epgs_using_function resource already includes the ID of the AEP in its path. It might be more convenient to either eliminate the access generic attribute or emphasize its meaning and usage in the documentation.

Thanks!

**Comment by akinross** [comment] 2024-01-15 17:19
Hi @kozhabergenova,

Apologies that this cause unexpected behaviour and disruptions. Since this is expected behaviour from the provider we will have a look at improving documentation for this type of behaviour, thank you for raising this to our attention.

A thing that you could have a look at, is the usage of data-sources. This way it will be reading the config in to state, instead of managing it. You would still face similar issue that if the value would change at a later stage it will trigger changes. 

Anther option perhaps would be to explore [lifecycle](https://developer.hashicorp.com/terraform/tutorials/state/resource-lifecycle) attribute. For instance determining prevent_destroy or ignore_changes, to safeguard against those scenarios.

I will be closing this issue.

**Closed by akinross** 2024-01-15 17:19 UTC
