### ISSUE TITLE
aci_bgp_peer_connectivity_profile:   local_asn should support to be empty

### ISSUE THREAD

**Issue by camrossi** [CiscoDevNet/terraform-provider-aci#412] opened 2021-05-24 00:49 UTC
A BGP Peer can be configure with an empty  local_asn. 
Currently the aci_bgp_peer_connectivity_profile sets it to "0" if the local_asn is not specified or if is set to "".

This is an invalid config. We need to support empty or 1 to 4294967295

Also deleting the bgpLocalAsnP object after as a workaround 
```
  class_name = "bgpLocalAsnP"
      content = {
        "status" = "deleted"
```
result in the aci_bgp_peer_connectivity_profile to crash with ``` Error: Error retriving Object: Object may not exists``` as it still expect the bgpLocalAsnP object to exist

**Comment by scotttyso** [comment] 2021-05-24 18:31
This is a duplicate of issue #369.  It is already in triage.

**Closed** 2021-06-15 21:16 UTC
Labels: bug, crest-triage
