### ISSUE TITLE
aci_rest_module with snmpClientP should access subnets for client address

### ISSUE THREAD

**Issue by scotttyso** [CiscoDevNet/terraform-provider-aci#1087] opened 2023-08-03 14:22 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### APIC version and APIC Platform

* V 6.0.2 and on-prem/cloud-aws/cloud-azure/all.

### Affected Resource(s)

* aci_rest_managed

### Terraform Configuration Files

```hcl
# module.fabric["default"].aci_rest_managed.snmp_policy_client_group_client_servers["default:ooband:10.101.128.24"]:
resource "aci_rest_managed" "snmp_policy_client_group_client_servers" {
    class_name = "snmpClientP"
    content    = {
        "addr"      = "10.101.128.0/24"
        "name"      = "LNX1"
        "nameAlias" = ""
        "userdom"   = ":all:"
    }
    dn         = "uni/fabric/snmppol-default/clgrp-ooband/client-[10.101.128.0/24]"
    id         = "uni/fabric/snmppol-default/clgrp-ooband/client-[10.101.128.0/24]"
}
```

### Panic Output

```
Error: property name of client-[10.101.128.0/24] failed validation for value '10.101.128.0/24'
```

### Expected Behavior

subnets should be supported as client groups, at least I should say the UI accepts it.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by akinross** [comment] 2023-09-12 10:11
Hi @scotttyso, I am unable to reproduce this issue. Please let me know if you still have the error. If so please provide more details on your configuration. I will proceed with closure of issue if no additional information is provided.

**Comment by akinross** [comment] 2023-09-19 08:40
Unreproducible, thus closing issue.

**Closed by akinross** 2023-09-19 08:40 UTC
