### ISSUE TITLE
Create resource and data source for consumer label in L3Out

### ISSUE THREAD

**Issue by shrsr** [CiscoDevNet/terraform-provider-aci#979] opened 2022-12-20 18:39 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### APIC version and APIC Platform

all

### Affected Resource(s)

New resource and data source
Example DN: uni/tn-module_l3out_tf_tenant/out-module_l3out/conslbl-hcloudGolfLabel
Class Name: l3extConsLbl

### Terraform Configuration Files
Equivalent rest managed resource-

```hcl
resource "aci_rest_managed" "l3out_consumer_label" {
  dn         = "${aci_l3_outside.l3out.id}/conslbl-hcloudGolfLabel"
  class_name = "l3extConsLbl"
  content = {
    name = "hcloudGolfLabel"
  }
}
```

**Comment by mfr-6** [comment] 2023-06-19 08:15
Hi, this is what I'm currently working on, i'll keep this issue updated.

**Comment by shrsr** [comment] 2023-06-19 10:01
@mfr-6 Thanks.

**Comment by lhercot** [comment] 2023-12-22 07:32
Duplicate of #934 

@mfr-6 sorry for the confusion if you are still working on this but Akini included this as part of #1113

**Comment by lhercot** [comment] 2023-12-22 07:32
Duplicate of https://github.com/CiscoDevNet/terraform-provider-aci/issues/934

**Closed by lhercot** 2023-12-22 07:32 UTC
Labels: new-data-source, new-resource
