### ISSUE TITLE
Contract Subject. Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by scotttyso** [CiscoDevNet/terraform-provider-aci#1064] opened 2023-06-22 10:45 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v1.4.5
on linux_amd64
+ provider registry.terraform.io/ciscodevnet/aci v2.8.0
+ provider registry.terraform.io/ciscodevnet/mso v0.10.0
+ provider registry.terraform.io/netascode/utils v0.2.5

Your version of Terraform is out of date! The latest version
is 1.5.1. You can update by downloading from https://www.terraform.io/downloads.html
```

### APIC version and APIC Platform

* V 6.0.2 and on-prem

### Affected Resource(s)

* aci_contract_subject

### Terraform Configuration Files

```hcl
resource "aci_contract_subject" "contract_subjects" {
  apply_both_directions         = "yes"
  cons_match_t                  = "AtleastOne"
  contract_dn                   = "uni/tn-common/brc-any"
  name                          = "any"
  prio                          = "unspecified"
  prov_match_t                  = "AtleastOne"
  rev_flt_ports                 = "yes"
  target_dscp                   = "unspecified"
}
```

### Panic Output

╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.built_in_tenants["common"].aci_contract_subject.contract_subjects["any:any"], provider
│ "provider[\"registry.terraform.io/ciscodevnet/aci\"]" produced an unexpected new value: Root resource was present, but now
│ absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
### Expected Behavior

It should have worked.
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by micronemo** [comment] 2023-06-25 15:44
you can use as workaround set the versione to 2.5.2 inside the provider

**Comment by scotttyso** [comment] 2023-06-26 11:33
@micronemo - I have updated other resources like bgp to new requirements in 0.2.8, so I just switched this to aci_rest_managed.  But they still need to fix the resource.  Thank you for your comments.

**Comment by sajagana** [comment] 2023-06-30 12:32
Hi @scotttyso,

The aci_contract_subject resource issue was fixed as part of this PR: https://github.com/CiscoDevNet/terraform-provider-aci/pull/1056. I just tested with the latest master source code. But the fix is not yet released.

**Comment by lhercot** [comment] 2023-07-01 10:07
I just released v2.9.0. Please let us know if the issue is now fixed.

**Comment by lhercot** [comment] 2023-07-07 21:09
@scotttyso Have you had the time to check if the latest release has fixed the issue?

**Comment by scotttyso** [comment] 2023-07-08 19:10
@lhercot Issue is resolved

**Closed** 2023-07-10 17:29 UTC
